# Generated by Django 4.2.26 on 2025-11-21 15:16

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('max_depth', models.IntegerField(blank=True, null=True)),
                ('max_pages', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='models_craw_status_e1ad54_idx'), models.Index(fields=['requested_at'], name='models_craw_request_cef73b_idx')],
            },
        ),
    ]
