# Generated by Django 4.2.26 on 2025-11-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('storage_key_raw', models.CharField(blank=True, max_length=512, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='models.crawljob')),
            ],
            options={
                'unique_together': {('job', 'url')},
            },
        ),
    ]
