# Generated by Django 4.2.26 on 2025-11-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='search_index_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
