# Generated by Django 4.2.26 on 2025-11-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_page_search_index_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='models.crawljob'),
        ),
    ]
